stages:
  check_data:
    cmd: python check_data.py
    deps:
      - check_data.py
      - data/salaries.csv
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
      - data/salaries.csv
    outs:
      - data/train.csv
      - data/test.csv
  train:
    cmd: python train.py
    deps:
      - train.py
      - data/train.csv
    outs:
      - models/model.pkl
  tune:
    cmd: python tune.py
    deps:
      - tune.py
      - data/test.csv
    outs: []